[package]
name = "muuk"
version = "1.0.0"

[library.muuk]
include = ["include"]
sources = [
    "src/muuk.cpp",
    "src/util.cpp",
    "src/logger.cpp",
    "src/muukfiler.cpp",
    "src/muukbuilder.cpp",
    "src/ninjagen.cpp",
    "src/muuklockgen.cpp",
]
modules = ["prototyping/modules/test_modules/bcwrdll.ixx"]

[library.muuk.dependencies]
spdlog = "v1.15.1"
zip = "v0.3.3"
json = "v3.11.3"
argparse = "v3.2"
glob = "v0.3"
cracklib = "v0.0.3"

[build.bin]
dependencies = { "muuk" = "v1.0.0" }
sources = ["src/main.cpp"]
gflags = ["/std:c++20", "/utf-8", "/EHsc", "/FS"]

[build.test]
dependencies = { "muuk" = "v1.0.0", "googletest" = "v1.15.2" }
sources = ["tests/internal/muuk_test.cpp"]
executable = "muuk_tests"
include = []
gflags = ["/std:c++20", "/utf-8", "/EHsc", "/FS"]

[clean]
patterns = ["*.obj", "*.lib", "*.pdb"]
